[package]
name = "athan"
version = "0.1.0"
edition = "2024"
description = "Lightweight and modern Islamic prayer times app"

[profile.dev]
debug = 0
strip = true

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true

[features]
default = ["detect"]
cli = ["dep:argp"]
hijri = ["dep:icu_calendar"]
detect = ["dep:minreq"]

[dependencies]
thiserror = "2"
time = { version = "0.3", features = ["formatting", "macros"] }
icu_calendar = { version = "2", default-features = false, features = ["compiled_data"], optional = true }
serde = { version = "1", features = ["derive"] }
argp = { version = "0.4", optional = true }
tokio = { version = "1", features = ["rt", "sync"] }
minreq = { version = "2", features = ["json-using-serde"], optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
iced = { version = "0.14", default-features = false, features = ["wgpu", "tokio", "thread-pool", "wayland"] }
ksni = { version = "0.3", features = ["tokio"] }

[target.'cfg(target_os = "windows")'.dependencies]
tray-icon = "0.24"

[target.'cfg(not(target_os = "linux"))'.dependencies]
iced = { version = "0.14", default-features = false, features = ["wgpu", "tokio", "thread-pool"] }
